version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dlm-service-log-filter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5j1qz8qxayzd"
s3_prefix = "dlm-service-log-filter"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
