AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dlm-service-log-filter

  Sample SAM Template for dlm-service-log-filter

Globals:
  Function:
    Timeout: 60

Resources:
  ErrorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub "dlm-service-errorlog-${AWS::Region}"
      RetentionInDays: 14
  LogFilter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: log-filter/
      Handler: app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          ERRORLOG_GROUP_NAME: !Ref ErrorLogGroup

#Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#  HelloWorldFunction:
#    Description: "Hello World Lambda Function ARN"
#    Value: !GetAtt HelloWorldFunction.Arn
#  HelloWorldFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt HelloWorldFunctionRole.Arn
